# Setup
title:               Foundations of Deep Learning
tagline:             NYU Tandon, Spring 2022
description:         >- # this means to ignore newlines until "url:"
  Quicklinks
url:                 https://chinmayhegde.github.io
baseurl:             '/fodl' # the subpath of your site, e.g. /blog

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for entries
collections:
  posts:
    output: true
    future: true

# Markdown specs
markdown: kramdown

kramdown:
  footnote_backlink: "&#x21a9;&#xfe0e;"
  enable_coderay: false
#  math_engine: null # pending https://github.com/github/pages-gem/pull/545

# Exclusions from the final site
exclude:
  - vendor
  - README.md
  - LICENSE.md
  - Gemfile*
  - proof.gemspec

# Theme
remote_theme: "mahrud/proof"
